config:
  mode: auto
  word: lingvo
  phrase: multitran

  log: log/dictionary.log
  db: db/dictionary.sqlite3
  
history:
  path: "./.history" 
  size: 1000
  perms: <%= File::WRONLY | File::CREAT | File::TRUNC %>
    
providers:
  lingvo: LingvoYandex
  multitran: Multitran